FROM osixia/openldap:1.5.0

RUN sed -i \
    -e 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' \
    -e 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' \
    -e '/buster-updates/d' \
    -e '/buster-backports/d' \
    /etc/apt/sources.list \
    && apt-get update -qq \
    && apt-get install -y -qq iptables \
    && rm -rf /var/lib/apt/lists/*
