name: Rust Format Check

on:
  push:
  pull_request:
    paths:
      - 'src/**'
      - 'test/unit'
      - 'test/integration'

env:
  CARGO_TERM_COLOR: always

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run cargo format check
        id: rust-format-check
        run: |
          cargo fmt --check

