name: Nightly Packaging

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  Get_GIT_SHA:
    name: Get commit SHA
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.value }}
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get SHA
        id: sha
        run: |
          echo "value=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get version for container packages
        id: version
        run: |
          VERSION=$(grep '^version = ' Cargo.toml | sed 's/.*"\(.*\)"/\1/')
          GIT_SHA=$(git rev-parse --short HEAD)
          if [[ "$VERSION" = *-dev ]]; then
            VERSION="${VERSION}+${GIT_SHA}"
          fi
          echo "value=${VERSION}" >> $GITHUB_OUTPUT


  Container_Packages:
    name: Container-based packages
    needs: Get_GIT_SHA
    uses: ./.github/workflows/packages.yml
    with:
      version: ${{ needs.Get_GIT_SHA.outputs.version }}
